// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bili.dart';
import 'api/desktop_lyric.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 225858282;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_melune',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleAppName();

  String crateApiBiliBiliCleanTitle({required String title});

  Future<BiliExtractedAudio> crateApiBiliBiliExtractAudio({
    required String bvid,
    required PlatformInt64 aid,
    required PlatformInt64 cid,
    required int qualityId,
  });

  Future<List<BiliFavoriteFolder>> crateApiBiliBiliFavoriteFolders();

  Future<BiliSearchPage> crateApiBiliBiliFavoriteTracks({
    required PlatformInt64 mediaId,
    required int page,
  });

  Future<BiliHistoryPage> crateApiBiliBiliHistory({
    required PlatformInt64 cursorMax,
    required PlatformInt64 cursorViewAt,
  });

  Future<BiliInitResult> crateApiBiliBiliInit({required String cookieDir});

  Future<void> crateApiBiliBiliLogout();

  Future<List<BiliTrack>> crateApiBiliBiliMusicRank();

  Future<List<BiliTrack>> crateApiBiliBiliMusicRecommend();

  Future<List<BiliTrack>> crateApiBiliBiliMusicRegion({required int page});

  Future<BiliUser> crateApiBiliBiliNav();

  Future<List<BiliTrack>> crateApiBiliBiliNewSongs();

  Future<List<BiliLyricLine>> crateApiBiliBiliOfficialLyrics({
    required String bvid,
    required PlatformInt64 cid,
  });

  Future<String> crateApiBiliBiliProxyUrl({required String audioUrl});

  Future<BiliQrCode> crateApiBiliBiliQrGenerate();

  Future<BiliQrPoll> crateApiBiliBiliQrPoll({required String qrcodeKey});

  Future<BiliSearchPage> crateApiBiliBiliSearch({
    required String keyword,
    required int page,
  });

  Future<List<BiliTrack>> crateApiBiliBiliSeasonTracks({
    required PlatformInt64 mid,
    required PlatformInt64 seasonId,
  });

  Future<List<BiliTrack>> crateApiBiliBiliVideoPages({required String bvid});

  void crateApiDesktopLyricDesktopLyricSet({
    required bool visible,
    required bool locked,
    required bool liked,
    required String coverUrl,
    required String previous,
    required String current,
    required String next,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleAppName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAppNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppNameConstMeta =>
      const TaskConstMeta(debugName: "app_name", argNames: []);

  @override
  String crateApiBiliBiliCleanTitle({required String title}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBiliBiliCleanTitleConstMeta,
        argValues: [title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliCleanTitleConstMeta =>
      const TaskConstMeta(debugName: "bili_clean_title", argNames: ["title"]);

  @override
  Future<BiliExtractedAudio> crateApiBiliBiliExtractAudio({
    required String bvid,
    required PlatformInt64 aid,
    required PlatformInt64 cid,
    required int qualityId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bvid, serializer);
          sse_encode_i_64(aid, serializer);
          sse_encode_i_64(cid, serializer);
          sse_encode_i_32(qualityId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_extracted_audio,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliExtractAudioConstMeta,
        argValues: [bvid, aid, cid, qualityId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliExtractAudioConstMeta =>
      const TaskConstMeta(
        debugName: "bili_extract_audio",
        argNames: ["bvid", "aid", "cid", "qualityId"],
      );

  @override
  Future<List<BiliFavoriteFolder>> crateApiBiliBiliFavoriteFolders() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_favorite_folder,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliFavoriteFoldersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliFavoriteFoldersConstMeta =>
      const TaskConstMeta(debugName: "bili_favorite_folders", argNames: []);

  @override
  Future<BiliSearchPage> crateApiBiliBiliFavoriteTracks({
    required PlatformInt64 mediaId,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(mediaId, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_search_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliFavoriteTracksConstMeta,
        argValues: [mediaId, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliFavoriteTracksConstMeta =>
      const TaskConstMeta(
        debugName: "bili_favorite_tracks",
        argNames: ["mediaId", "page"],
      );

  @override
  Future<BiliHistoryPage> crateApiBiliBiliHistory({
    required PlatformInt64 cursorMax,
    required PlatformInt64 cursorViewAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(cursorMax, serializer);
          sse_encode_i_64(cursorViewAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_history_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliHistoryConstMeta,
        argValues: [cursorMax, cursorViewAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliHistoryConstMeta => const TaskConstMeta(
    debugName: "bili_history",
    argNames: ["cursorMax", "cursorViewAt"],
  );

  @override
  Future<BiliInitResult> crateApiBiliBiliInit({required String cookieDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cookieDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_init_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliInitConstMeta,
        argValues: [cookieDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliInitConstMeta =>
      const TaskConstMeta(debugName: "bili_init", argNames: ["cookieDir"]);

  @override
  Future<void> crateApiBiliBiliLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliLogoutConstMeta =>
      const TaskConstMeta(debugName: "bili_logout", argNames: []);

  @override
  Future<List<BiliTrack>> crateApiBiliBiliMusicRank() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliMusicRankConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliMusicRankConstMeta =>
      const TaskConstMeta(debugName: "bili_music_rank", argNames: []);

  @override
  Future<List<BiliTrack>> crateApiBiliBiliMusicRecommend() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliMusicRecommendConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliMusicRecommendConstMeta =>
      const TaskConstMeta(debugName: "bili_music_recommend", argNames: []);

  @override
  Future<List<BiliTrack>> crateApiBiliBiliMusicRegion({required int page}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliMusicRegionConstMeta,
        argValues: [page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliMusicRegionConstMeta =>
      const TaskConstMeta(debugName: "bili_music_region", argNames: ["page"]);

  @override
  Future<BiliUser> crateApiBiliBiliNav() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_user,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliNavConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliNavConstMeta =>
      const TaskConstMeta(debugName: "bili_nav", argNames: []);

  @override
  Future<List<BiliTrack>> crateApiBiliBiliNewSongs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliNewSongsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliNewSongsConstMeta =>
      const TaskConstMeta(debugName: "bili_new_songs", argNames: []);

  @override
  Future<List<BiliLyricLine>> crateApiBiliBiliOfficialLyrics({
    required String bvid,
    required PlatformInt64 cid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bvid, serializer);
          sse_encode_i_64(cid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_lyric_line,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliOfficialLyricsConstMeta,
        argValues: [bvid, cid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliOfficialLyricsConstMeta =>
      const TaskConstMeta(
        debugName: "bili_official_lyrics",
        argNames: ["bvid", "cid"],
      );

  @override
  Future<String> crateApiBiliBiliProxyUrl({required String audioUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(audioUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliProxyUrlConstMeta,
        argValues: [audioUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliProxyUrlConstMeta =>
      const TaskConstMeta(debugName: "bili_proxy_url", argNames: ["audioUrl"]);

  @override
  Future<BiliQrCode> crateApiBiliBiliQrGenerate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_qr_code,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliQrGenerateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliQrGenerateConstMeta =>
      const TaskConstMeta(debugName: "bili_qr_generate", argNames: []);

  @override
  Future<BiliQrPoll> crateApiBiliBiliQrPoll({required String qrcodeKey}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(qrcodeKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_qr_poll,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliQrPollConstMeta,
        argValues: [qrcodeKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliQrPollConstMeta =>
      const TaskConstMeta(debugName: "bili_qr_poll", argNames: ["qrcodeKey"]);

  @override
  Future<BiliSearchPage> crateApiBiliBiliSearch({
    required String keyword,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyword, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bili_search_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliSearchConstMeta,
        argValues: [keyword, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliSearchConstMeta => const TaskConstMeta(
    debugName: "bili_search",
    argNames: ["keyword", "page"],
  );

  @override
  Future<List<BiliTrack>> crateApiBiliBiliSeasonTracks({
    required PlatformInt64 mid,
    required PlatformInt64 seasonId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(mid, serializer);
          sse_encode_i_64(seasonId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliSeasonTracksConstMeta,
        argValues: [mid, seasonId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliSeasonTracksConstMeta =>
      const TaskConstMeta(
        debugName: "bili_season_tracks",
        argNames: ["mid", "seasonId"],
      );

  @override
  Future<List<BiliTrack>> crateApiBiliBiliVideoPages({required String bvid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bvid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bili_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBiliBiliVideoPagesConstMeta,
        argValues: [bvid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBiliBiliVideoPagesConstMeta =>
      const TaskConstMeta(debugName: "bili_video_pages", argNames: ["bvid"]);

  @override
  void crateApiDesktopLyricDesktopLyricSet({
    required bool visible,
    required bool locked,
    required bool liked,
    required String coverUrl,
    required String previous,
    required String current,
    required String next,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(visible, serializer);
          sse_encode_bool(locked, serializer);
          sse_encode_bool(liked, serializer);
          sse_encode_String(coverUrl, serializer);
          sse_encode_String(previous, serializer);
          sse_encode_String(current, serializer);
          sse_encode_String(next, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDesktopLyricDesktopLyricSetConstMeta,
        argValues: [
          visible,
          locked,
          liked,
          coverUrl,
          previous,
          current,
          next,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDesktopLyricDesktopLyricSetConstMeta =>
      const TaskConstMeta(
        debugName: "desktop_lyric_set",
        argNames: [
          "visible",
          "locked",
          "liked",
          "coverUrl",
          "previous",
          "current",
          "next",
        ],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BiliAudioQuality dco_decode_bili_audio_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BiliAudioQuality(
      id: dco_decode_i_32(arr[0]),
      label: dco_decode_String(arr[1]),
      detail: dco_decode_String(arr[2]),
      bandwidth: dco_decode_i_64(arr[3]),
      vipOnly: dco_decode_bool(arr[4]),
      audioUrl: dco_decode_String(arr[5]),
    );
  }

  @protected
  BiliExtractedAudio dco_decode_bili_extracted_audio(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BiliExtractedAudio(
      track: dco_decode_bili_track(arr[0]),
      qualities: dco_decode_list_bili_audio_quality(arr[1]),
      selectedId: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  BiliFavoriteFolder dco_decode_bili_favorite_folder(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BiliFavoriteFolder(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      mediaCount: dco_decode_i_32(arr[2]),
      coverUrl: dco_decode_String(arr[3]),
    );
  }

  @protected
  BiliHistoryPage dco_decode_bili_history_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BiliHistoryPage(
      tracks: dco_decode_list_bili_track(arr[0]),
      hasMore: dco_decode_bool(arr[1]),
      cursorMax: dco_decode_i_64(arr[2]),
      cursorViewAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  BiliInitResult dco_decode_bili_init_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BiliInitResult(
      proxyBase: dco_decode_String(arr[0]),
      user: dco_decode_bili_user(arr[1]),
    );
  }

  @protected
  BiliLyricLine dco_decode_bili_lyric_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BiliLyricLine(
      fromMs: dco_decode_u_32(arr[0]),
      toMs: dco_decode_u_32(arr[1]),
      content: dco_decode_String(arr[2]),
    );
  }

  @protected
  BiliQrCode dco_decode_bili_qr_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BiliQrCode(
      url: dco_decode_String(arr[0]),
      qrcodeKey: dco_decode_String(arr[1]),
    );
  }

  @protected
  BiliQrPoll dco_decode_bili_qr_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BiliQrPoll(
      code: dco_decode_i_32(arr[0]),
      message: dco_decode_String(arr[1]),
      loggedIn: dco_decode_bool(arr[2]),
    );
  }

  @protected
  BiliSearchPage dco_decode_bili_search_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BiliSearchPage(
      items: dco_decode_list_bili_track(arr[0]),
      page: dco_decode_u_32(arr[1]),
      totalPages: dco_decode_u_32(arr[2]),
      totalResults: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  BiliTrack dco_decode_bili_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return BiliTrack(
      id: dco_decode_String(arr[0]),
      bvid: dco_decode_String(arr[1]),
      aid: dco_decode_i_64(arr[2]),
      cid: dco_decode_i_64(arr[3]),
      title: dco_decode_String(arr[4]),
      artist: dco_decode_String(arr[5]),
      albumTitle: dco_decode_String(arr[6]),
      coverUrl: dco_decode_String(arr[7]),
      durationSec: dco_decode_u_32(arr[8]),
      playCount: dco_decode_i_64(arr[9]),
      audioUrl: dco_decode_String(arr[10]),
      pageCount: dco_decode_u_32(arr[11]),
      seasonId: dco_decode_i_64(arr[12]),
      upMid: dco_decode_i_64(arr[13]),
    );
  }

  @protected
  BiliUser dco_decode_bili_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BiliUser(
      isLogin: dco_decode_bool(arr[0]),
      mid: dco_decode_i_64(arr[1]),
      name: dco_decode_String(arr[2]),
      face: dco_decode_String(arr[3]),
      isVip: dco_decode_bool(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<BiliAudioQuality> dco_decode_list_bili_audio_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bili_audio_quality).toList();
  }

  @protected
  List<BiliFavoriteFolder> dco_decode_list_bili_favorite_folder(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bili_favorite_folder).toList();
  }

  @protected
  List<BiliLyricLine> dco_decode_list_bili_lyric_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bili_lyric_line).toList();
  }

  @protected
  List<BiliTrack> dco_decode_list_bili_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bili_track).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BiliAudioQuality sse_decode_bili_audio_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_bandwidth = sse_decode_i_64(deserializer);
    var var_vipOnly = sse_decode_bool(deserializer);
    var var_audioUrl = sse_decode_String(deserializer);
    return BiliAudioQuality(
      id: var_id,
      label: var_label,
      detail: var_detail,
      bandwidth: var_bandwidth,
      vipOnly: var_vipOnly,
      audioUrl: var_audioUrl,
    );
  }

  @protected
  BiliExtractedAudio sse_decode_bili_extracted_audio(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_track = sse_decode_bili_track(deserializer);
    var var_qualities = sse_decode_list_bili_audio_quality(deserializer);
    var var_selectedId = sse_decode_i_32(deserializer);
    return BiliExtractedAudio(
      track: var_track,
      qualities: var_qualities,
      selectedId: var_selectedId,
    );
  }

  @protected
  BiliFavoriteFolder sse_decode_bili_favorite_folder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_mediaCount = sse_decode_i_32(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    return BiliFavoriteFolder(
      id: var_id,
      title: var_title,
      mediaCount: var_mediaCount,
      coverUrl: var_coverUrl,
    );
  }

  @protected
  BiliHistoryPage sse_decode_bili_history_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tracks = sse_decode_list_bili_track(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    var var_cursorMax = sse_decode_i_64(deserializer);
    var var_cursorViewAt = sse_decode_i_64(deserializer);
    return BiliHistoryPage(
      tracks: var_tracks,
      hasMore: var_hasMore,
      cursorMax: var_cursorMax,
      cursorViewAt: var_cursorViewAt,
    );
  }

  @protected
  BiliInitResult sse_decode_bili_init_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proxyBase = sse_decode_String(deserializer);
    var var_user = sse_decode_bili_user(deserializer);
    return BiliInitResult(proxyBase: var_proxyBase, user: var_user);
  }

  @protected
  BiliLyricLine sse_decode_bili_lyric_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fromMs = sse_decode_u_32(deserializer);
    var var_toMs = sse_decode_u_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    return BiliLyricLine(
      fromMs: var_fromMs,
      toMs: var_toMs,
      content: var_content,
    );
  }

  @protected
  BiliQrCode sse_decode_bili_qr_code(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_qrcodeKey = sse_decode_String(deserializer);
    return BiliQrCode(url: var_url, qrcodeKey: var_qrcodeKey);
  }

  @protected
  BiliQrPoll sse_decode_bili_qr_poll(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_i_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_loggedIn = sse_decode_bool(deserializer);
    return BiliQrPoll(
      code: var_code,
      message: var_message,
      loggedIn: var_loggedIn,
    );
  }

  @protected
  BiliSearchPage sse_decode_bili_search_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_bili_track(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_totalPages = sse_decode_u_32(deserializer);
    var var_totalResults = sse_decode_i_64(deserializer);
    return BiliSearchPage(
      items: var_items,
      page: var_page,
      totalPages: var_totalPages,
      totalResults: var_totalResults,
    );
  }

  @protected
  BiliTrack sse_decode_bili_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_bvid = sse_decode_String(deserializer);
    var var_aid = sse_decode_i_64(deserializer);
    var var_cid = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_albumTitle = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_durationSec = sse_decode_u_32(deserializer);
    var var_playCount = sse_decode_i_64(deserializer);
    var var_audioUrl = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    var var_seasonId = sse_decode_i_64(deserializer);
    var var_upMid = sse_decode_i_64(deserializer);
    return BiliTrack(
      id: var_id,
      bvid: var_bvid,
      aid: var_aid,
      cid: var_cid,
      title: var_title,
      artist: var_artist,
      albumTitle: var_albumTitle,
      coverUrl: var_coverUrl,
      durationSec: var_durationSec,
      playCount: var_playCount,
      audioUrl: var_audioUrl,
      pageCount: var_pageCount,
      seasonId: var_seasonId,
      upMid: var_upMid,
    );
  }

  @protected
  BiliUser sse_decode_bili_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isLogin = sse_decode_bool(deserializer);
    var var_mid = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_face = sse_decode_String(deserializer);
    var var_isVip = sse_decode_bool(deserializer);
    return BiliUser(
      isLogin: var_isLogin,
      mid: var_mid,
      name: var_name,
      face: var_face,
      isVip: var_isVip,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<BiliAudioQuality> sse_decode_list_bili_audio_quality(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BiliAudioQuality>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bili_audio_quality(deserializer));
    }
    return ans_;
  }

  @protected
  List<BiliFavoriteFolder> sse_decode_list_bili_favorite_folder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BiliFavoriteFolder>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bili_favorite_folder(deserializer));
    }
    return ans_;
  }

  @protected
  List<BiliLyricLine> sse_decode_list_bili_lyric_line(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BiliLyricLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bili_lyric_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<BiliTrack> sse_decode_list_bili_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BiliTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bili_track(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bili_audio_quality(
    BiliAudioQuality self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_i_64(self.bandwidth, serializer);
    sse_encode_bool(self.vipOnly, serializer);
    sse_encode_String(self.audioUrl, serializer);
  }

  @protected
  void sse_encode_bili_extracted_audio(
    BiliExtractedAudio self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bili_track(self.track, serializer);
    sse_encode_list_bili_audio_quality(self.qualities, serializer);
    sse_encode_i_32(self.selectedId, serializer);
  }

  @protected
  void sse_encode_bili_favorite_folder(
    BiliFavoriteFolder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_32(self.mediaCount, serializer);
    sse_encode_String(self.coverUrl, serializer);
  }

  @protected
  void sse_encode_bili_history_page(
    BiliHistoryPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_bili_track(self.tracks, serializer);
    sse_encode_bool(self.hasMore, serializer);
    sse_encode_i_64(self.cursorMax, serializer);
    sse_encode_i_64(self.cursorViewAt, serializer);
  }

  @protected
  void sse_encode_bili_init_result(
    BiliInitResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.proxyBase, serializer);
    sse_encode_bili_user(self.user, serializer);
  }

  @protected
  void sse_encode_bili_lyric_line(
    BiliLyricLine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.fromMs, serializer);
    sse_encode_u_32(self.toMs, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_bili_qr_code(BiliQrCode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.qrcodeKey, serializer);
  }

  @protected
  void sse_encode_bili_qr_poll(BiliQrPoll self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_bool(self.loggedIn, serializer);
  }

  @protected
  void sse_encode_bili_search_page(
    BiliSearchPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_bili_track(self.items, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.totalPages, serializer);
    sse_encode_i_64(self.totalResults, serializer);
  }

  @protected
  void sse_encode_bili_track(BiliTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.bvid, serializer);
    sse_encode_i_64(self.aid, serializer);
    sse_encode_i_64(self.cid, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.albumTitle, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_u_32(self.durationSec, serializer);
    sse_encode_i_64(self.playCount, serializer);
    sse_encode_String(self.audioUrl, serializer);
    sse_encode_u_32(self.pageCount, serializer);
    sse_encode_i_64(self.seasonId, serializer);
    sse_encode_i_64(self.upMid, serializer);
  }

  @protected
  void sse_encode_bili_user(BiliUser self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isLogin, serializer);
    sse_encode_i_64(self.mid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.face, serializer);
    sse_encode_bool(self.isVip, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_bili_audio_quality(
    List<BiliAudioQuality> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bili_audio_quality(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bili_favorite_folder(
    List<BiliFavoriteFolder> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bili_favorite_folder(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bili_lyric_line(
    List<BiliLyricLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bili_lyric_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bili_track(
    List<BiliTrack> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bili_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
