// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bili.dart';
import 'api/desktop_lyric.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BiliAudioQuality dco_decode_bili_audio_quality(dynamic raw);

  @protected
  BiliExtractedAudio dco_decode_bili_extracted_audio(dynamic raw);

  @protected
  BiliFavoriteFolder dco_decode_bili_favorite_folder(dynamic raw);

  @protected
  BiliHistoryPage dco_decode_bili_history_page(dynamic raw);

  @protected
  BiliInitResult dco_decode_bili_init_result(dynamic raw);

  @protected
  BiliLyricLine dco_decode_bili_lyric_line(dynamic raw);

  @protected
  BiliQrCode dco_decode_bili_qr_code(dynamic raw);

  @protected
  BiliQrPoll dco_decode_bili_qr_poll(dynamic raw);

  @protected
  BiliSearchPage dco_decode_bili_search_page(dynamic raw);

  @protected
  BiliTrack dco_decode_bili_track(dynamic raw);

  @protected
  BiliUpProfile dco_decode_bili_up_profile(dynamic raw);

  @protected
  BiliUser dco_decode_bili_user(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<BiliAudioQuality> dco_decode_list_bili_audio_quality(dynamic raw);

  @protected
  List<BiliFavoriteFolder> dco_decode_list_bili_favorite_folder(dynamic raw);

  @protected
  List<BiliLyricLine> dco_decode_list_bili_lyric_line(dynamic raw);

  @protected
  List<BiliTrack> dco_decode_list_bili_track(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BiliAudioQuality sse_decode_bili_audio_quality(SseDeserializer deserializer);

  @protected
  BiliExtractedAudio sse_decode_bili_extracted_audio(
    SseDeserializer deserializer,
  );

  @protected
  BiliFavoriteFolder sse_decode_bili_favorite_folder(
    SseDeserializer deserializer,
  );

  @protected
  BiliHistoryPage sse_decode_bili_history_page(SseDeserializer deserializer);

  @protected
  BiliInitResult sse_decode_bili_init_result(SseDeserializer deserializer);

  @protected
  BiliLyricLine sse_decode_bili_lyric_line(SseDeserializer deserializer);

  @protected
  BiliQrCode sse_decode_bili_qr_code(SseDeserializer deserializer);

  @protected
  BiliQrPoll sse_decode_bili_qr_poll(SseDeserializer deserializer);

  @protected
  BiliSearchPage sse_decode_bili_search_page(SseDeserializer deserializer);

  @protected
  BiliTrack sse_decode_bili_track(SseDeserializer deserializer);

  @protected
  BiliUpProfile sse_decode_bili_up_profile(SseDeserializer deserializer);

  @protected
  BiliUser sse_decode_bili_user(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<BiliAudioQuality> sse_decode_list_bili_audio_quality(
    SseDeserializer deserializer,
  );

  @protected
  List<BiliFavoriteFolder> sse_decode_list_bili_favorite_folder(
    SseDeserializer deserializer,
  );

  @protected
  List<BiliLyricLine> sse_decode_list_bili_lyric_line(
    SseDeserializer deserializer,
  );

  @protected
  List<BiliTrack> sse_decode_list_bili_track(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bili_audio_quality(
    BiliAudioQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bili_extracted_audio(
    BiliExtractedAudio self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bili_favorite_folder(
    BiliFavoriteFolder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bili_history_page(
    BiliHistoryPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bili_init_result(
    BiliInitResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bili_lyric_line(BiliLyricLine self, SseSerializer serializer);

  @protected
  void sse_encode_bili_qr_code(BiliQrCode self, SseSerializer serializer);

  @protected
  void sse_encode_bili_qr_poll(BiliQrPoll self, SseSerializer serializer);

  @protected
  void sse_encode_bili_search_page(
    BiliSearchPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bili_track(BiliTrack self, SseSerializer serializer);

  @protected
  void sse_encode_bili_up_profile(BiliUpProfile self, SseSerializer serializer);

  @protected
  void sse_encode_bili_user(BiliUser self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_bili_audio_quality(
    List<BiliAudioQuality> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bili_favorite_folder(
    List<BiliFavoriteFolder> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bili_lyric_line(
    List<BiliLyricLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bili_track(
    List<BiliTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
