// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_i64`, `audio_quality_detail`, `audio_quality_from_item`, `audio_quality_label`, `audio_quality_rank`, `clean_title`, `collect_audio_qualities`, `collect_hot_items`, `collect_music_archives`, `duration_sec_of`, `empty_nav`, `extract_book_title`, `first_i64`, `first_str`, `https_url`, `is_music_entry`, `is_music_label`, `is_music_tid`, `is_non_song_tid`, `is_rejected_song_title`, `is_song_duration`, `is_song_tid`, `is_vip_audio`, `is_vip`, `json_list`, `json_str`, `looks_like_song_collection`, `map_archive_item`, `map_fav_item`, `map_history_item`, `map_lyric_line`, `map_music_center`, `map_search_item`, `map_user`, `map_video_pages`, `page_count_of`, `parse_duration`, `pick_audio_quality`, `season_id_of`, `stream_url`, `strip_html`, `subtitle_rank`, `track_id`, `unique_by_bvid`, `up_mid_of`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BiliState`

Future<BiliInitResult> biliInit({required String cookieDir}) =>
    RustLib.instance.api.crateApiBiliBiliInit(cookieDir: cookieDir);

Future<String> biliProxyUrl({required String audioUrl}) =>
    RustLib.instance.api.crateApiBiliBiliProxyUrl(audioUrl: audioUrl);

Future<BiliUser> biliNav() => RustLib.instance.api.crateApiBiliBiliNav();

Future<void> biliLogout() => RustLib.instance.api.crateApiBiliBiliLogout();

Future<BiliQrCode> biliQrGenerate() =>
    RustLib.instance.api.crateApiBiliBiliQrGenerate();

Future<BiliQrPoll> biliQrPoll({required String qrcodeKey}) =>
    RustLib.instance.api.crateApiBiliBiliQrPoll(qrcodeKey: qrcodeKey);

Future<BiliSearchPage> biliSearch({
  required String keyword,
  required int page,
}) => RustLib.instance.api.crateApiBiliBiliSearch(keyword: keyword, page: page);

Future<List<BiliTrack>> biliVideoPages({required String bvid}) =>
    RustLib.instance.api.crateApiBiliBiliVideoPages(bvid: bvid);

Future<List<BiliTrack>> biliSeasonTracks({
  required PlatformInt64 mid,
  required PlatformInt64 seasonId,
}) => RustLib.instance.api.crateApiBiliBiliSeasonTracks(
  mid: mid,
  seasonId: seasonId,
);

Future<BiliExtractedAudio> biliExtractAudio({
  required String bvid,
  required PlatformInt64 aid,
  required PlatformInt64 cid,
  required int qualityId,
}) => RustLib.instance.api.crateApiBiliBiliExtractAudio(
  bvid: bvid,
  aid: aid,
  cid: cid,
  qualityId: qualityId,
);

Future<List<BiliTrack>> biliMusicRank() =>
    RustLib.instance.api.crateApiBiliBiliMusicRank();

Future<List<BiliTrack>> biliNewSongs() =>
    RustLib.instance.api.crateApiBiliBiliNewSongs();

Future<List<BiliTrack>> biliMusicRegion({required int page}) =>
    RustLib.instance.api.crateApiBiliBiliMusicRegion(page: page);

Future<List<BiliTrack>> biliMusicRecommend() =>
    RustLib.instance.api.crateApiBiliBiliMusicRecommend();

Future<List<BiliFavoriteFolder>> biliFavoriteFolders() =>
    RustLib.instance.api.crateApiBiliBiliFavoriteFolders();

Future<BiliSearchPage> biliFavoriteTracks({
  required PlatformInt64 mediaId,
  required int page,
}) => RustLib.instance.api.crateApiBiliBiliFavoriteTracks(
  mediaId: mediaId,
  page: page,
);

Future<BiliHistoryPage> biliHistory({
  required PlatformInt64 cursorMax,
  required PlatformInt64 cursorViewAt,
}) => RustLib.instance.api.crateApiBiliBiliHistory(
  cursorMax: cursorMax,
  cursorViewAt: cursorViewAt,
);

Future<List<BiliLyricLine>> biliOfficialLyrics({
  required String bvid,
  required PlatformInt64 cid,
}) => RustLib.instance.api.crateApiBiliBiliOfficialLyrics(bvid: bvid, cid: cid);

String biliCleanTitle({required String title}) =>
    RustLib.instance.api.crateApiBiliBiliCleanTitle(title: title);

class BiliAudioQuality {
  final int id;
  final String label;
  final String detail;
  final PlatformInt64 bandwidth;
  final bool vipOnly;
  final String audioUrl;

  const BiliAudioQuality({
    required this.id,
    required this.label,
    required this.detail,
    required this.bandwidth,
    required this.vipOnly,
    required this.audioUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      detail.hashCode ^
      bandwidth.hashCode ^
      vipOnly.hashCode ^
      audioUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliAudioQuality &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          detail == other.detail &&
          bandwidth == other.bandwidth &&
          vipOnly == other.vipOnly &&
          audioUrl == other.audioUrl;
}

class BiliExtractedAudio {
  final BiliTrack track;
  final List<BiliAudioQuality> qualities;
  final int selectedId;

  const BiliExtractedAudio({
    required this.track,
    required this.qualities,
    required this.selectedId,
  });

  @override
  int get hashCode => track.hashCode ^ qualities.hashCode ^ selectedId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliExtractedAudio &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          qualities == other.qualities &&
          selectedId == other.selectedId;
}

class BiliFavoriteFolder {
  final PlatformInt64 id;
  final String title;
  final int mediaCount;
  final String coverUrl;

  const BiliFavoriteFolder({
    required this.id,
    required this.title,
    required this.mediaCount,
    required this.coverUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ mediaCount.hashCode ^ coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliFavoriteFolder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          mediaCount == other.mediaCount &&
          coverUrl == other.coverUrl;
}

class BiliHistoryPage {
  final List<BiliTrack> tracks;
  final bool hasMore;
  final PlatformInt64 cursorMax;
  final PlatformInt64 cursorViewAt;

  const BiliHistoryPage({
    required this.tracks,
    required this.hasMore,
    required this.cursorMax,
    required this.cursorViewAt,
  });

  @override
  int get hashCode =>
      tracks.hashCode ^
      hasMore.hashCode ^
      cursorMax.hashCode ^
      cursorViewAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliHistoryPage &&
          runtimeType == other.runtimeType &&
          tracks == other.tracks &&
          hasMore == other.hasMore &&
          cursorMax == other.cursorMax &&
          cursorViewAt == other.cursorViewAt;
}

class BiliInitResult {
  final String proxyBase;
  final BiliUser user;

  const BiliInitResult({required this.proxyBase, required this.user});

  @override
  int get hashCode => proxyBase.hashCode ^ user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliInitResult &&
          runtimeType == other.runtimeType &&
          proxyBase == other.proxyBase &&
          user == other.user;
}

class BiliLyricLine {
  final int fromMs;
  final int toMs;
  final String content;

  const BiliLyricLine({
    required this.fromMs,
    required this.toMs,
    required this.content,
  });

  @override
  int get hashCode => fromMs.hashCode ^ toMs.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliLyricLine &&
          runtimeType == other.runtimeType &&
          fromMs == other.fromMs &&
          toMs == other.toMs &&
          content == other.content;
}

class BiliQrCode {
  final String url;
  final String qrcodeKey;

  const BiliQrCode({required this.url, required this.qrcodeKey});

  @override
  int get hashCode => url.hashCode ^ qrcodeKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliQrCode &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          qrcodeKey == other.qrcodeKey;
}

class BiliQrPoll {
  final int code;
  final String message;
  final bool loggedIn;

  const BiliQrPoll({
    required this.code,
    required this.message,
    required this.loggedIn,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ loggedIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliQrPoll &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          loggedIn == other.loggedIn;
}

class BiliSearchPage {
  final List<BiliTrack> items;
  final int page;
  final int totalPages;
  final PlatformInt64 totalResults;

  const BiliSearchPage({
    required this.items,
    required this.page,
    required this.totalPages,
    required this.totalResults,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      page.hashCode ^
      totalPages.hashCode ^
      totalResults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliSearchPage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          totalPages == other.totalPages &&
          totalResults == other.totalResults;
}

class BiliTrack {
  final String id;
  final String bvid;
  final PlatformInt64 aid;
  final PlatformInt64 cid;
  final String title;
  final String artist;
  final String albumTitle;
  final String coverUrl;
  final int durationSec;
  final PlatformInt64 playCount;
  final String audioUrl;
  final int pageCount;
  final PlatformInt64 seasonId;
  final PlatformInt64 upMid;

  const BiliTrack({
    required this.id,
    required this.bvid,
    required this.aid,
    required this.cid,
    required this.title,
    required this.artist,
    required this.albumTitle,
    required this.coverUrl,
    required this.durationSec,
    required this.playCount,
    required this.audioUrl,
    required this.pageCount,
    required this.seasonId,
    required this.upMid,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bvid.hashCode ^
      aid.hashCode ^
      cid.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      albumTitle.hashCode ^
      coverUrl.hashCode ^
      durationSec.hashCode ^
      playCount.hashCode ^
      audioUrl.hashCode ^
      pageCount.hashCode ^
      seasonId.hashCode ^
      upMid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bvid == other.bvid &&
          aid == other.aid &&
          cid == other.cid &&
          title == other.title &&
          artist == other.artist &&
          albumTitle == other.albumTitle &&
          coverUrl == other.coverUrl &&
          durationSec == other.durationSec &&
          playCount == other.playCount &&
          audioUrl == other.audioUrl &&
          pageCount == other.pageCount &&
          seasonId == other.seasonId &&
          upMid == other.upMid;
}

class BiliUser {
  final bool isLogin;
  final PlatformInt64 mid;
  final String name;
  final String face;
  final bool isVip;

  const BiliUser({
    required this.isLogin,
    required this.mid,
    required this.name,
    required this.face,
    required this.isVip,
  });

  @override
  int get hashCode =>
      isLogin.hashCode ^
      mid.hashCode ^
      name.hashCode ^
      face.hashCode ^
      isVip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiliUser &&
          runtimeType == other.runtimeType &&
          isLogin == other.isLogin &&
          mid == other.mid &&
          name == other.name &&
          face == other.face &&
          isVip == other.isVip;
}
