// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 桌面歌词已改由 Flutter 第二窗口渲染，这里只保留 FRB 符号以免重新 generate。
void desktopLyricSet({
  required bool visible,
  required bool locked,
  required bool liked,
  required String coverUrl,
  required String previous,
  required String current,
  required String next,
}) => RustLib.instance.api.crateApiDesktopLyricDesktopLyricSet(
  visible: visible,
  locked: locked,
  liked: liked,
  coverUrl: coverUrl,
  previous: previous,
  current: current,
  next: next,
);
