// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 桌面歌词：Windows 上开一层置顶分层窗口，其它平台为空操作。
void desktopLyricSet({
  required bool visible,
  required bool locked,
  required bool liked,
  required String coverUrl,
  required String previous,
  required String current,
  required String next,
}) => RustLib.instance.api.crateApiDesktopLyricDesktopLyricSet(
  visible: visible,
  locked: locked,
  liked: liked,
  coverUrl: coverUrl,
  previous: previous,
  current: current,
  next: next,
);
